"""add_call_type_and_agent_environment_to_call

Revision ID: 45b6b7aee2eb
Revises: 69dc2fd8d8d5
Create Date: 2025-07-06 22:21:01.829836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '45b6b7aee2eb'
down_revision: Union[str, Sequence[str], None] = '69dc2fd8d8d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    calltype_enum = sa.Enum('inbound', 'outbound', name='calltype')
    calltype_enum.create(op.get_bind(), checkfirst=True)

    agentenv_enum = sa.Enum('production', 'development', name='agentenvironment')
    agentenv_enum.create(op.get_bind(), checkfirst=True)

    # 1. Agregar columnas como nullable con default
    op.add_column('call', sa.Column('call_type', sa.Enum('inbound', 'outbound', name='calltype'), nullable=True, server_default='inbound'))
    op.add_column('call', sa.Column('agent_environment', sa.Enum('production', 'development', name='agentenvironment'), nullable=True, server_default='production'))

    # 2. Actualizar filas existentes para que tengan el valor por defecto
    op.execute("UPDATE call SET call_type='inbound' WHERE call_type IS NULL;")
    op.execute("UPDATE call SET agent_environment='production' WHERE agent_environment IS NULL;")

    # 3. Alterar las columnas para que sean NOT NULL
    op.alter_column('call', 'call_type', nullable=False)
    op.alter_column('call', 'agent_environment', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call', 'agent_environment')
    op.drop_column('call', 'call_type')
    agentenv_enum = sa.Enum('production', 'development', name='agentenvironment')
    calltype_enum = sa.Enum('inbound', 'outbound', name='calltype')
    agentenv_enum.drop(op.get_bind(), checkfirst=True)
    calltype_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

