"""Initial migration

Revision ID: 73a7d006cd2e
Revises: 99d2080565ab
Create Date: 2025-07-05 20:48:24.989666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '73a7d006cd2e'
down_revision: Union[str, Sequence[str], None] = '99d2080565ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assistant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('call_start_time', sa.DateTime(), nullable=True),
    sa.Column('call_ended_time', sa.DateTime(), nullable=True),
    sa.Column('customer_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recording_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ended_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('call_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_call_id'), 'call', ['call_id'], unique=True)
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_type', sa.Enum('HUMAN', 'LLM', 'VAPI', name='evaluatortype'), nullable=False),
    sa.Column('reviewer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('evaluation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('check', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status_feedback_engineer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comments_engineer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['call.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation')
    op.drop_index(op.f('ix_call_call_id'), table_name='call')
    op.drop_table('call')
    # ### end Alembic commands ###
