"""TimesStamMixin

Revision ID: 99d2080565ab
Revises: b93e1c15560c
Create Date: 2025-07-05 16:03:50.179536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d2080565ab'
down_revision: Union[str, Sequence[str], None] = 'b93e1c15560c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinic', sa.Column('created', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinic', 'created')
    # ### end Alembic commands ###
